const dbConfig = require("../config/db.config");
const mongoose = require("mongoose");
mongoose.Promise = global.Promise;
const db = {};
db.mongoose = mongoose;
db.url = dbConfig.url;
db.members = require("./member.model.js")(mongoose);
// db.ROLES = ["user", "admin", "moderator"];
module.exports = db;
